### ISSUE TITLE
How to replace Box with Shape?

### ISSUE THREAD

**Issue by tommaoer** [yanghtr/Sync2Gen#1]
Hi, 
Very promising results and interesting work!
When I run your code, I found the released code only produce the box layouts in a scene. And in your [paper ](https://arxiv.org/pdf/2108.13499.pdf)(Sec 5.1), the method uses a pre-trained model [49] to get the latent codes for each shape and retrieve a new shape with three PCA components during the test.
But, [49] is a GAN-based generative model, so how to obtain the latent code for each object's shape.
It is very nice if you can provide more details/codes on how to replace generated boxes with shapes.

Thanks!

**Comment by YeolYao** [comment]
> Hi, Very promising results and interesting work! When I run your code, I found the released code only produce the box layouts in a scene. And in your [paper ](https://arxiv.org/pdf/2108.13499.pdf)(Sec 5.1), the method uses a pre-trained model [49] to get the latent codes for each shape and retrieve a new shape with three PCA components during the test. But, [49] is a GAN-based generative model, so how to obtain the latent code for each object's shape. It is very nice if you can provide more details/codes on how to replace generated boxes with shapes.
> 
> Thanks!

Hello, I have the same question, have you solved this problem now?
