### ISSUE TITLE
Obtain the latent code for each object's shape

### ISSUE THREAD

**Issue by YeolYao** [yanghtr/Sync2Gen#3]
Hello! When I run your code, I found the released code only produce the box layouts in a scene. And in your [paper ](https://arxiv.org/pdf/2108.13499.pdf)(Sec 5.1), the method uses a pre-trained model [49] to get the latent codes for each shape and retrieve a new shape with three PCA components during the test.
But, [49] is a GAN-based generative model, so how to obtain the latent code for each object's shape.
 Could you provide more details/codes on how to replace generated boxes with shapes?
 Thanks a lot!

**Comment by yanghtr** [comment]
In this repo we do not release the codes that use learned latent codes. For simplicity you can just randomly select the model from the training dataset. Note that in the evaluation only the layouts are considered. The relationship between the texture/geometry of different objects in the scene is not evaluated.
